name: changedMailBox
version: ${project.version}
main: org.system.changedMailBox.ChangedMailBoxPlugin
api-version: 1.20
commands:
  setmailbox:
    description: 进入邮箱绑定模式，右键箱子完成绑定
    usage: /setmailbox
    permission: changedmailbox.setmailbox
  bag:
    description: 打开你的物品暂存箱
    usage: /bag
    permission: changedmailbox.bag
  mail:
    description: 邮箱管理命令
    usage: /mail unlock
    permission: changedmailbox.mail
permissions:
  changedmailbox.setmailbox:
    description: 允许使用 /setmailbox 命令
    default: true
  changedmailbox.bag:
    description: 允许使用 /bag 命令
    default: true
  changedmailbox.mail:
    description: 允许使用 /mail 命令
    default: true